  
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "tboeghk"
  - package-ecosystem: "java"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20
    reviewers:
      - "tboeghk"