  
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    ignore:
      - dependency-name: "openjdk"
        versions: ["12.x", "13.x", "14.x", "15.x", "16.x"]
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "tboeghk"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20
    reviewers:
      - "tboeghk"