dist: bionic

language: java
jdk: 
  - openjdk12

services:
- docker

env:
  global:
  - secure: ipAwRljZXXi09usPSOuUQT7lViUKWrt1gYPyTIP2POo2TJxhI97TN6WzYoj2nkSLtfulR73yQy72kS0h7zM0dBCndO9S23z2qgNfV6FsF5Eo3JFLgKr9tnaGeMjL05oW0VaHWQzk5lXFD95Er88YJreQbbge80F5Xr5tSQs3+C/LdOfqzdzS2OSaAiV/E8aA9RokwkR+a4ium3zewz4jfyEk17KL8wzPI5aO9xhxbi0YA96+DN/jDG5Cb9TeQQ3zuoXav69r5+BcFD5PpVwEenxe2SUnrp3V7CCwxzXudHiKVugJS+pNgIPo/bxRlNPktSRMkCokFd6x27D1ffMs/0ZIfV3OEWK+7WwOuYQjd6f3ZN9Kjp/7fHZOpEXgSzaxy0AekijJYh4lRnDh/NFX05dd+DRZ+qwghYrzPH5f4Sx1+GVT2HGzST8ybgOUYf805VqjLrhNLaTiFig1OoEwRjFmTc9BtbaBv/+4vVOVTODLeEX95s9ZOb/6QYDciLza25yxrZwSenlReunKQ4g169F5LzDI7rs9ZuRwZ0EH8hcgGi6zXGYDiz3eXboT3jYNmq1F75mAcZPqOUFGGd3LPxj4cpLWEjvC+h1KmlzsmgCTbCv5iJnypBHjPo+TmyL8n1t+pidLkFaHLJBP/2mfG7yrrU3YXo7zkZIu3AF9Yko=
  - secure: qqrbFmYRcM3EKTkKmA2qIR72ZYed5625lfpfIvFb3E7+8jXvpvhwDphoUucEID7apgqdf9aOU6/HQ7eNMPs6KMmL6Gmg1fmFDj1de6aK4wVkGWdokRQIA34G8+J7YHapad/7jXWR5nEWOAzbj9BgUb7oXRX4XhVaErJ8trUkbeSlRxERv81EQq4gtUyy+J6xqX54zKw0QcgnHmk9vyhaJdBAXo417XR1Q/O5T9gO0V8onPQBTWktpoxTJIdeM9adq9IbbHWsPCQFLHQa6ETMCeBGZO5JcUvHYWKi1kjV5aEFulOFhAp6pGpj7RAL3grb+Hh7h04ChLMzxwDPrqdRXRRsGcxcLlcL/5fPMy9qrYne3U1D91W70fDY19rqR2QYBEk+LWDzWM8vG5/nKgF3IUrN40nj4jdIL6q4TN8zlhNUgQjAj35ZoynWlNExfRbZaTcxkl1k8X9WOWZlnmKb7xD86REKna8O8H2CMPS+ap7EXD+hb4jkFU3r7vbO4mDaUECw7RuRz/bMJPZ/QHLNUlZQrYloW5Ks8FReF6meuCGQDA4lgu3K3+mlVQ8IULsQIw7gf8hgNSmwkfIHPO5QNfraCoN1frgu5FlQWTxf4RqOsd4Oq14XbpuA/S3CtdlS56wMMuHRlTfx3KO69fcbtK7lkLdgJ4n/ir09byHPxLA=

script:
- mvn clean verify
- docker build -t observabilitystack/geoip-api:latest -t observabilitystack/geoip-api:$(date
  +%Y-%V) .

after_success:
- if [ "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}" == "master" ]; then
- docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
- docker push observabilitystack/geoip-api:latest
- docker push observabilitystack/geoip-api:$(date +%Y-%V)
- fi
