CITY_DB_FILE: /srv/GeoLite2-City.mmdb
server:
  tomcat:
    max-threads: 16
    accesslog:
      enabled: true
      directory: /dev
      file-date-format:
      prefix: stdout
      suffix:
      rotate: false
      request-attributes-enabled: true
