name: geoip-api docker ci build

# Execute the Docker CI build only on master (for now)
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}    
    
    - uses: actions/checkout@v2

    - name: Determine tag
      run: "::set-output name=tag::date +%Y-%V"

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        #platforms: linux/amd64,linux/arm64
        push: false
        build-args: |
          MAXMIND_LICENSE_KEY=${{ secrets.MAXMIND_LICENSE_KEY }}
        tags: |
          observabilitystack/geoip:${{ steps.determine_tag.outputs.tag }}
          observabilitystack/geoip:latest